language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - make check
  
branches:
  only:
  - master

notifications:
  email:
    - pdassier@free.fr
